spring.datasource.url=jdbc:postgresql://localhost:5432/avito
spring.datasource.username=postgres
spring.datasource.password=0331SQL
spring.jpa.hibernate.ddl-auto=update
path.to.avatars.folder=/avatars
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
server.port = 8080
path.to.ad.photo = market/ads/photos
path.to.user.images = market/users/images
path.to.default.user.image= market/users/images/default-image.jpg